default: &default
  adapter: postgresql
  pool: 5
  host: <%= Rails.application.credentials.dig(:database, :host) %>
  database: <%= Rails.application.credentials.dig(:database, :name) %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  timeout: 5000

test:
  <<: *default
development:
  <<: *default
production:
  <<: *default